### ISSUE TITLE
Some General Questions

### ISSUE THREAD

**Issue by vedantdave97** [seohongpark/METRA#1]
Hello @seohongpark 
First of all, thank you for the three awesome papers: LSD, CSD and METRA. They are easy to follow and an a delight to read. I have some general questions regarding them (and METRA) in general (some things that I exactly don't understand):

1. I'm trying to grasp the application of the Wasserstein metric in your approach. At the end of the day, the objective aims to impose a temporal constraint. If I relate it to the LSD paper, I can say that instead of Lipschitz constraint, you use this temporal constraint (Everything else would remain the same, no matter what). I don't exactly get it.
 
2. Any of the code (amongst the three methods) runs for 2M epochs (--n_epochs 2000001). This computes for almost 400M+ environmental steps and takes almost 1+ day to compute (I checked, its running on GPU (RTX 4090)). However, when running URLB codes, it takes about 1hr per seed on the same PC.

Thanks in advance. Good luck for ICLR.

Kind Regards,
VD

**Comment by seohongpark** [comment]
Hi VD, thanks for the questions.

1. As mentioned in Section 4.2, all three methods (LSD, CSD, and METRA) can be interpreted as maximizing I_W(S; Z) but with different underlying distance metrics. LSD uses Euclidean distances and METRA uses temporal distances. As such, they only differ by the constraints: `|φ(s) - φ(s')| <= |s - s'|` (LSD) vs. `|φ(s) - φ(s')| <= 1` (METRA).

2. `n_epochs=2000001` is just a dummy value. It usually takes less than 12 hours to train METRA on state-based environments and 12-24 hours on pixel-based environments (on A5000 GPUs). Please see Figures 8 and 9 for plots with respect to wall clock time.

**Comment by vedantdave97** [comment]
Hello @seohongpark 
Thanks a lot for resolving the issues.

Kind Regards,
VD
