### ISSUE TITLE
Reproducing downstream performance of METRA

### ISSUE THREAD

**Issue by jack32666** [seohongpark/METRA#2]
Hi, I really appreciate your work!

I wonder how can I reproduce downstream performance of METRA in Figure 6. I couldn’t locate the code for downstream learning in the repository. 

Any guidance or assistance on this would be greatly appreciated. Thanks! @seohongpark

**Comment by seohongpark** [comment]
Hi jack326,

Thanks for your interest in this work! Cleaning up the code for downstream evaluation is still on our to-do list, but in the meantime, I can send you the implementation in the development branch via email.

**Comment by jack32666** [comment]
Thank you for your prompt response and for considering my request!

I really appreciate your willingness to share the implementation from the development branch.

Could you send the code to my email address at [jack326@naver.com]? It would be really helpful.

Thanks once again for your assistance! @seohongpark

**Comment by sixIceWings** [comment]
Hi, @seohongpark.

I am also interested in downstream performance of METRA, especially zero-shot goal-reaching. I believe it will have a significant impact on ROS. 
It's a bit difficult for me about coding. Could you send the code about downstream evaluation to my email address [gu_food@foxmail.com] ?

Looking forward to your reply.

**Comment by DMU-XMU** [comment]
Hi, @seohongpark,

METRA is a great work, we're also learning the downstream implementation details of METRA. Could you send the downstream code to my email address at (dyliang@stu.xmu.edu.cn)? Thank you.

Waiting for your reply. thank you.

**Comment by bofusun** [comment]
Hi, @seohongpark ,

We are also interested in the downstream implementation of METRA. Would it be possible for you to share the downstream code with us? You can send it to my email address [sunjingbo1111@gmail.com](url).  Your assistance would be greatly appreciated.

Looking forward to your response. Thank you in advance.

**Comment by leekwoon** [comment]
Hi, @seohongpark ,

Thanks for your excellent work and I am also interested in the downstream implementation of METRA.  Could you share the code about the downstraem evaluation to my email address (kyowoon.lee1924@gmail.com)? 

Looking forward to your reply. Thank you.

**Comment by n3il666** [comment]
Hi @seohongpark ,

Thanks for the amazing work. I am also interested in the downstream implementation of METRA. Could you share the code on that to tzhong1688@gmail.com?

Thanks in advance.

**Comment by heatz123** [comment]
Hello, @seohongpark,

Thank you for the great work and for significantly contributing to the field of unsupervised skill discovery! I am particularly interested in the code for downstream tasks. If possible, could you please send the code to heatz123@snu.ac.kr? I would greatly appreciate it.

Thanks again!

**Comment by JaeHyung-Kim** [comment]
Hi @seohongpark ,

Thanks for your nice work. I am also interested in the downstream implementation of METRA. So could you please share the code on that to kimjaehyung@kaist.ac.kr?

Looking forward to your reply. 
Thank you!

**Comment by yangzhao-666** [comment]
Hi @seohongpark,
Thanks for open-sourcing the codebase. I'm interested in the downstream task evaluation and zero-shot goal-reaching implementation. Was wondering is it possible to share that part of the code? If yes, could you please share it to yangzhaooba@gmail.com? Thank you very much!

**Comment by pastapeter** [comment]
Hello @seohongpark 
Thanks for the work. I'm MS student at Seoul National University. I am really interested in the downstream implementation of METRA. Could you please share the code to [pissaitoworks@gmail.com](mailto:pissaitoworks@gmail.com)?

**Comment by pastapeter** [comment]
hi @seohongpark 
sorry for the mistake 
I miswrote the email address..
Could you share downstream implementation code to [pissaitworks@gmail.com](mailto:pissaitworks@gmail.com)?
Thank you so much!

**Comment by doinalot** [comment]
Hi @seohongpark
I was deeply impressed by METRA and found it incredibly inspiring. Recently, i am trying to reproduce the downstream implementation, but I’m having some difficulties. Would it be possible for you to share your downstream implementation code to niwniw93@gmail.com?

**Comment by shihminyang** [comment]
Hi @seohongpark!
Thanks for your excellent work! I am also interested in the implementation of downstream tasks in METRA. Could you please send me the code via email (ethansmin.yang@gmail.com)?
Thank you so much!

**Comment by Giho-Kim** [comment]
Hi @seohongpark!

I greatly appreciate your outstanding work. I'm particularly interested in how downstream tasks are implemented in METRA. Could you please send me the relevant code at chicioue512@snu.ac.kr?

Thank you very much!

**Comment by think-z** [comment]
Hi, @seohongpark !

Thanks for your excellent work and I am also interested in the downstream implementation of METRA. Could you share the code about the downstream learning to my email address ([zthink02@gmail.com](mailto:zthink02@gmail.com))?

Looking forward to your response. Thank you in advance!

**Comment by zal0302** [comment]
Hi, @seohongpark !

I’m very impressed by your work and am especially curious about the implementation details of the downstream tasks in METRA. Would it be possible for you to send the corresponding code to liuza@mail.nankai.edu.cn? I would truly appreciate it.
