### ISSUE TITLE
Questions about PhiPlot

### ISSUE THREAD

**Issue by 21yrm** [seohongpark/METRA#4]
What does the PhiPlot graph mean? And how are the Phi trajectories mentioned in the paper obtained?

**Comment by seohongpark** [comment]
Hi 21yrm, PhiPlot just plots $\phi(s)$. The phi trajectories in the paper are also $\phi(s)$ trajectories from randomly sampled $z$'s.

**Comment by 21yrm** [comment]
I don't understand what 'plot phi' is trying to convey, nor do I understand what this graph illustrates. Please explain, thank you.
