### ISSUE TITLE
Regarding Conflict In Dependencies

### ISSUE THREAD

**Issue by YashKumthekar8** [seohongpark/METRA#5]
Hello this is Yash Kumthekar. I am currently pursuing Masters In Computer Science from IIT Bombay. I was going through your code base and want to run the files to get some idea about the METRA system. But there was some issue regarding Mujoco version as in requirements.txt it is having version 2.2.1 but after executing main.py it is providing some errors pointing towards mujoco version should be less than 2.1.x. Can you provide some information to resolve this issue so that I can setup this codebase in my machine and try to generate the experiments you provided in the research paper.

Thank you.

**Comment by seohongpark** [comment]
Hi,

We used *both* `mujoco==2.2.1` (for DMC environments like Quadruped/Humanoid) and `mujoco-py==2.1.2.14` (for Gym environments like Ant/HalfCheetah). I previously found that running `pip install -r requirements.txt --no-deps` is enough, and I might recommend running this command on a fresh conda environment.
