### ISSUE TITLE
Figure 3. How to Define success rate on Kitchen Task.

### ISSUE THREAD

**Issue by FrankSinatral** [seohongpark/METRA#6]
Thanks for your great work, but I am wondering how you conduct your experiment in kitchen task, i.e. how to calculate success rate on each subtask in Figure 3. I notice that you rollout 48 trajectories for evaluation during training, meaning that there are 60% of these trajectories complete Kettle subtask?

**Comment by seohongpark** [comment]
Hi FrankSinatral, we measured whether any of the 48 evaluation trajectories happened to achieve the Kettle subtask (i.e., 0 or 1 for each seed), and averaged over 8 seeds; as a result, the possible values in Fig. 3 are {0, 0.125, 0.25, ..., 0.875, 1.0}.

**Comment by FrankSinatral** [comment]
Thanks for your reply! So it means that in Fig.3 the average success rate (over 8 seeds) of Kettle subtask for example is 0.625, meaning that there are 48*0.625=30 achieving the Kettle subtask, where in code it could be interpreted as given this trajectory (traj in code), the maximum value of traj['env_infos']['metric_success_task_relevant/goal_5'] (5 refers to the Kettle subtask) equals to 1, it seems that the calc_eval_metrics only calculates whether there exists a successful trajectory completing the subtask? Also, I am wondering how many epochs have you trained to obtain the result in Fig.3? Thanks a lot!

**Comment by seohongpark** [comment]
I think I was probably not entirely clear in the above response: for Kettle, for each seed, we first check whether there exists at least 1 trajectory (out of 48 evaluation trajectories) that happens to achieve the Kettle task, and then aggregate this boolean value (0/1) assigned to each seed over 8 seeds. We use the evaluation results at epoch 3250.

**Comment by FrankSinatral** [comment]
Thanks a lot! I understand your meaning!
