### ISSUE TITLE
Running CSD using METRA codebase

### ISSUE THREAD

**Issue by yangzhao-666** [seohongpark/METRA#7]
Hi Seohong,

As you mentioned in [comment of CSD repo](https://github.com/seohongpark/CSD-manipulation/issues/5#issuecomment-1817748065), METRA repo contains CSD implementation. Could you please indicate how can we run CSD using the METRA codebase?

Thanks for your help and time!

Best,
Zhao

**Comment by seohongpark** [comment]
Hi Zhao, you can use `--dual_dist s2_from_s --dual_lam 3000 --dual_slack 1e-06` to run CSD.
